version: "3.8"
services:
  #Pull existing postgres image from dockerhub
  postgres:
    image: postgres:15
    container_name: hotel-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hotelbooking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  #Build backend image and put the postgres image as a prerequisite
  backend:
    build: .
    container_name: hotel-backend
    image: hotel-booking-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hotelbooking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - postgres

volumes:
  pgdata:
