spring.application.name=Hotelbooking

# ---- DataSource ----
#Production Setup
#spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=${PGUSER}
#spring.datasource.password=${PGPASSWORD}

#Local Setup
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=create-drop


# ---- JPA / Hibernate ----
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ---- SQL ----
spring.sql.init.mode=never

# ---- Stripe ----
stripe.secret-key=${MOCK_STRIPE_SECRET_KEY:dummy_key_for_dev}

# ---- Spring ----
spring.main.allow-bean-definition-overriding=true
