# ---- Database ----
DB_URL=jdbc:h2:mem:testdb
DB_USER=sa
DB_PASSWORD=

# ---- Hibernate ----
spring.jpa.hibernate.ddl-auto=update

# ---- SQL Initialization ----

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ---- Stripe ----
stripe.secret-key=test

# ---- Cloudinary ----
cloudinary.cloud_name=test
cloudinary.api_key=test
cloudinary.api_secret=test


