spring.application.name=Hotelbooking

# Active profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE}

# ---- JPA / Hibernate ----
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ---- Spring ----
spring.main.allow-bean-definition-overriding=true


